name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs: 

  void_workflow: 
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous redundans builds
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}


  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: 17
    - name: install dependencies
      run: npm ci
    - name: lint
      run: npm run lint

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: 17
      - name: Install dependencies
        run: npm ci
      - name: test
        run: npm run test